module.exports = {
  ROLES: {
    ADMIN: 'ADMIN',
    MANAGER: 'MANAGER',
    SELLER: 'SELLER',
    WAREHOUSE: 'WAREHOUSE',
  },

  INVITATION_STATUS: {
    PENDING: 'PENDING',
    ACCEPTED: 'ACCEPTED',
    EXPIRED: 'EXPIRED',
    CANCELLED: 'CANCELLED',
  },

  SALE_STATUS: {
    PENDING: 'PENDING',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
    REFUNDED: 'REFUNDED',
  },

  STOCK_MOVEMENT: {
    ENTRY: 'ENTRY',
    EXIT: 'EXIT',
    TRANSFER: 'TRANSFER',
    ADJUSTMENT: 'ADJUSTMENT',
  },

  PAGINATION: {
    DEFAULT_PAGE: 1,
    DEFAULT_LIMIT: 20,
    MAX_LIMIT: 100,
  },

  INVITATION_EXPIRY_DAYS: 7,
};
